NetCoreFirstAppWithLayers/Models/ErrorViewModel.cs
namespace NetCoreFirstAppWithLayers.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NetCoreFirstAppWithLayers/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreFirstAppWithLayers.Models;
using System.Diagnostics;

namespace NetCoreFirstAppWithLayers.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NetCoreFirstAppWithLayers/Controllers/MedicamentoController.cs
using Microsoft.AspNetCore.Mvc;

namespace NetCoreFirstAppWithLayers.Controllers
{
    public class MedicamentoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

NetCoreFirstAppWithLayers/Controllers/TipoMedicamentoController.cs
using Microsoft.AspNetCore.Mvc;
using CapaNegocio;
using CapaEntidad;

namespace NetCoreFirstAppWithLayers.Controllers
{
    public class TipoMedicamentoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Inicio() {
            return View();
        }

        public IActionResult SinMenu()
        {
            return View();
        }

        //String
        public string Saludos()
        {
            return "Hello Friends";
        }

        public string SaludoNombre(string nombre)
        {
            return "Bienvenido " + nombre;
        }

        public string SaludoNombreApellido(string nombre, string apellido)
        {
            return "Bienvenido " + nombre + " " + apellido;
        }

        public int Number()
        {
            return 1;
        }

        public double NumeroDecimal()
        {
            return 12.5;
        }

        public List<TipoMedicamentoCLS> listarTipoMedicamento()
        {
            TipoMedicamentoBL objBL = new TipoMedicamentoBL();
            return objBL.listarMedicamentos();
        }
    }
}

NetCoreFirstAppWithLayers/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NetCoreFirstAppWithLayers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetCoreFirstAppWithLayers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NetCoreFirstAppWithLayers.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NetCoreFirstAppWithLayers</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" 
                                asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" 
                                asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="TipoMedicamento" asp-action="Index">Tipos de Medicamento</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="TipoMedicamento" asp-action="Inicio">Tipos de Medicamento - Inicio</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="TipoMedicamento" asp-action="SinMenu">Tipos de Medicamento - Sin Menu</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - NetCoreFirstAppWithLayers - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NetCoreFirstAppWithLayers/Views/TipoMedicamento/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Es el Index </h1>

NetCoreFirstAppWithLayers/Views/TipoMedicamento/Inicio.cshtml
@{
    ViewData["Title"] = "Inicio";
}

<h1>Inicio</h1>

<h2>Es la pagina Principal de proyecto</h2>

NetCoreFirstAppWithLayers/Views/TipoMedicamento/SinMenu.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SinMenu</title>
</head>
<body>
    <h1>Sin Menu</h1>
</body>
</html>